import { Button, VerticalBox, HorizontalBox, LineEdit, ScrollView, StandardListView, ListView } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "api2db";
    width: 500px;
    height: 750px;

    in-out property<string> error-output: "";
    in-out property<string> api-input: "";
    in-out property<string> db-input: "";
    in-out property<string> response-output: "";
    in-out property<string> preview-output: "";
    in-out property<string> status-code-output: "";
    in-out property <[int]> preview-key: [];

    callback api-response(string);
    callback api-response-dl(string);
    
    GridLayout {
        padding: 25px;
        spacing: 15px;
        Row {
            HorizontalBox {
                alignment: center;
                Text {
                    text: "\{error-output}";
                    color: red;
                    font-size: 10px;
                    width: 75px;
                }
            }
        }
        Row {
            HorizontalBox {
                alignment: center;
                Text {
                    text: "API:";
                    font-size: 15px;
                }
                api_string := LineEdit {
                    font-size: 15px;
                    placeholder-text: "api string";
                    height: 20px;
                    width: 300px;
                }
                Text {
                    text: "\{status-code-output}";
                    color: white;
                    font-size: 15px;
                    width: 75px;
                }
            }
        }
        Row {
            HorizontalBox {
                Button {
                    text: "Test Connection";
                    height: 30px;
                    clicked => {
                        api-response(api_string.text);
                    }
                }
                Button {
                    text: "Download";
                    height: 30px;
                    clicked => {
                        api-response-dl(response-output);
                    }
                }
            }
        }
        Row {
            HorizontalLayout {
                ListView {
                    for string in preview-key: Rectangle {
                        height: 15px;
                        Text {
                            text: string;
                        }
                    }
                }
            }
        }
        Row {
            HorizontalBox {
                Button { 
                    height: 30px;
                    text: "DynamoDB";
                }
                Button { 
                    height: 30px;
                    text: "MongoDB"; 
                }
                Button { 
                    height: 30px;
                    text: "Postgres"; 
                }
            }
        }
        Row {
            HorizontalBox {
                alignment: center;
                Text {
                    text: "DB: \{root.db_input}";
                    font-size: 15px;
                }
                db_string := LineEdit {
                    font-size: 15px;
                    placeholder-text: "db string";
                    height: 20px;
                    width: 300px;
                }
            }
        }
        Row {
            VerticalBox {
                alignment: center;
                Text {
                    font-size: 15px;
                    text: "Schema:";
                }
            }
        }
        Row {
            HorizontalBox {
                alignment: center;
                Text {
                    font-size: 15px;
                    text: "TEST";
                }
            }
        }
        Row {
            Button {
                text: "Ingest";
                height: 30px;
                clicked => {
                    api-response(api_string.text);
                }
            }
        }
    }
}
